---
language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t reubenjames/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true reubenjames/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-172855385345"
  bucket_path: "docker-react"
  on:
    branch: master
