---
language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t reubenjames/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true reubenjames/docker-react npm run test
